### ISSUE TITLE
Existing Docker container are killing when i modified docker cloud profile

### ISSUE THREAD

**Issue by nchidipothu** [JeanRev/TeamcityDockerCloudPlugin#15]
Hi,

We have one docker cloud profile, where it has one linux host and with multiple docker images.

Lets assume, i modified anyone of docker image(not running) and saved, then running docker container is killing even build is running on that.

**Comment by JeanRev** [comment]
Hi @nchidipothu ! If I understand the issue correctly, then it probably relates to #14.

The plugin is tracking containers using both labels and environment variables. When a managed container (started by the plugin) is committed to a new image, those meta-data will be persisted as well. When a container is started from such image, the plugin will detect it, and since no internal state will be associated with it, destroy it.

This clean-up mechanism rightfully aims to dispose containers that may have survived a server shutdown, but it should not target containers that are derived from a plugin managed container.

This will probably not be part of the next release (to be released in the coming weeks), but will be addressed shortly afterward.
