### ISSUE TITLE
Docker API updated to 1.26?

### ISSUE THREAD

**Issue by jeandet** [JeanRev/TeamcityDockerCloudPlugin#24]
Hello when i try to create a container I get this issue:
```
run.var.teamcity.cloud.docker.client.BadRequestException: POST /v1.26/images/create: invocation failed with code 400 -- client is newer than server (client API version: 1.26, server API version: 1.24)
```
I use the latest version of this plugin.
Is it possible to downgrade API version on plugin side?

**Comment by JeanRev** [comment]
Hi @jeandet ,

Version 1.24 of the API is actually still supported. The internal docker client is supposed to first try to connect to the v1.26 endpoint, and fall back to the current engine version if it's older, but this API negotiation is not taking place as it should when testing containers (this must however not prevent the usage of productive containers, as long as their settings are correct).

This issue will be fixed in the next release, or you can also use the following preview artifact: [docker-cloud_0.4.2-SNAPSHOT_b5846fd.zip](https://tc.var.run/repository/download/TeamCityDockerCloudPlugin_Hotfix/187:id/docker-cloud_0.4.2-SNAPSHOT_b5846fd.zip?guest=1). Let me know if it solved your issue if you do.

**Comment by jeandet** [comment]
Ok thanks, the 4.2 snapshot solves this issue. This is great!

**Comment by JeanRev** [comment]
You're welcome, thank you for the feedback :-)
