### ISSUE TITLE
Specify Registry username and password

### ISSUE THREAD

**Issue by acraftydev** [JeanRev/TeamcityDockerCloudPlugin#7]
When specifying a custom docker image for agents we need to specify the username/password for the image registry, anonymous access is not supported (im using the docker registry built into nexus which doesn't support anonymous access https://www.sonatype.com/docker)

I'm happy to try to make pull request if happy to add this feature?

thanks

**Comment by sharov** [comment]
It'll be good to use docker config in an implementation of this feature. Because Amazon EC2 Container Registry (ECR) use tokens, with TTL 12 hours.

**Comment by JeanRev** [comment]
Support for registry authentication is indeed an important feature, and I already planned to work on it in the new few weeks.

PRs are always welcome :-)

There a several aspects of this feature that will need to be implemented.

1. Extending the plugin internal Docker client to handle authentication with the Docker Daemon. Authentication should permit to pull images hosted in V1 and V2 registries.
2. Extending the cloud configuration to store the user credentials.
3. Extending the cloud settings with the required UI components. Maybe as part of a sub-dialog, since the cloud image edition view is already overloaded.

Just let me know if you like to start working on one of those subjects, so we can design it more precisely.

**Comment by acraftydev** [comment]
i was initially looking at 2 and 3 and then using that to set "X-Registry-Auth" header in the createImage request.

Realistically going to take me a week or 2 to get into it as only have a bit of spare time in evenings. Once i've had time to get into it i can come back to discuss in more detail but don't want to hold up work if you plan to do it.

**Comment by JeanRev** [comment]
There is no time pressure.

Having another person looking at the code is highly profitable for the project, and I'm here to help if you have any question.

A few hints to get you started:
- I assume that the credentials will be managed as a property for a single image, you'll want to look at the corresponding java class: DockerImageConfig.
- You can add new fields in the cloud settings pages with this series of step:
    1. Modify the JSP page (docker-cloud-settings.jsp) to add you inputs. Their id must start with 'dockerCloudImage_' in oder to be imported in the 'view-model'. The view model is a Javascript map created automatically from the page DOM. The map keys are the field ids (without the 'dockerCloudImage_' prefix), and map values are the values of the fields themselves (as string).
    2. In docker-cloud.js, modify the _convertViewModelToSettings function to map the new field from the view model into the 'settings' object. This object will later be stringified into JSON and persisted as a configuration property for the plugin. You will likely store the credentials as part of the "Administration" settings object.
    3. Modify the _convertSettingsToViewModel function to provide the inverse mapping (settings to view-model). This function is used to populate back into the page the settings object that were umarshalled from the JSON.
    4. Read the new JSON property in the DockerImageConfig class.

You'll find examples in the code if you want to use dialogs (they are actually provided by the Teamcity javascript API), or if you want to validate fields along with error/warning messages. Don't hesitate to ask if you're unsure.

On my side, I'll try to see how the login process can be best implemented with the internal Docker client.

**Comment by acraftydev** [comment]
Shall we start a gitter https://gitter.im/ channe, mailing list or similar
to discuss in, i also have some other questions of some other changes?

thanks

**Comment by JeanRev** [comment]
Sure, here is a room for the issue:
https://gitter.im/TeamcityDockerCloudPlugin/registry-auth

**Comment by JeanRev** [comment]
@sharov Amazon ECRs seems to be indeed a special use case, since they rely solely on relatively short-lived one-time-password that you must regularly update through AWS.

Using the Docker host credential store is an option, since it can be externally managed (eg. cron)... But I would also take a look at the Amazon ECR SDK (the ability to retrieve the token automatically would be neat). I created a separate issue to keep track of this: #11
